### ISSUE TITLE
Any luck on compiling this on Ubuntu 12.04?

### ISSUE THREAD

**Issue by esn89** [thestinger/termite#126]
Has anyone managed to get this working?  There are quite a few vtes in there, but no mention of one bigger than 0.34.

I tried vte-common but that didn't seem to cut it.

**Comment by cgag** [comment]
This was helpful to me in getting it building on debian stretch, I'm glad it wasn't asked on IRC, as I'd have likely just given up on using termite.  Not sure why you'd want to avoid this kind of thread, but if you do,  I'd put a recommended IRC channel (or other means of support) in the readme.

**Comment by esn89** [comment]
If you guys like, I could make a wiki page for this project on how to get termite up and running from scratch.

**Comment by toogy** [comment]
@esn89 :+1: go on

**Comment by cgag** [comment]
That'd be great.  The main things I remember were finding the vte source, figuring out how to patch it by copying the patch file to the vte dir and running "patch -p1 -i expose_select_text.patch", and figuring how where to get vapigen (valac).  I also needed to install libgirepository1.0-dev, but I can't really remember why, but I don't think it was straight obvious from the configure error message.

**Comment by toogy** [comment]
Installing termite on Ubuntu is way too complicated... Can't we do something about it?

**Comment by thestinger** [comment]
It wouldn't need to patch VTE if upstream exposed the necessary functions for setting the cursor position, setting the text selection, toggling block selection and pausing/unpausing output. It doesn't add a significant amount of new API surface, especially since the coordinates for the cursor and selection are already exposed. They're apparently only interested in doing things that directly benefit GNOME Terminal. That's why this is unnecessary difficult. Take it up with the GNOME developers.

https://bugzilla.gnome.org/show_bug.cgi?id=679658

**Comment by thestinger** [comment]
See the last few comments in that bugzilla thread.

**Comment by thestinger** [comment]
There's now a fork of VTE, so you can download the tagged release from there and do the usual `./autogen.sh && make` to build it.

https://github.com/thestinger/vte-ng

**Comment by cgag** [comment]
Are they saying they want to implement selection and just provide an api for customizing keybindings? Feels more like an app than a library, maybe I don't fully understand their goals.  Thanks for forking, I just compiled against the fork and everything seems to work for me now.

**Comment by esn89** [comment]
I think now that thestinger forked the vte and patched it, we don't really need no guide, since most of the problems come from people struggling with vte patching and installation.

**Comment by thestinger** [comment]
@cgag: Yes, they're saying they won't accept a simple patch exposing the necessary APIs because terminals won't implicitly gain keyboard selection. Instead, they'll only accept a patch somehow implementing this *inside* VTE. I have no idea how that would be done considering how specific it is to the chosen design (i.e. they're probably not going to want a Vim mode). It also rules out the ability to do things like URL hints.

Anyway, I've had very bad experiences with GNOME so there's *no way* I'm developing large features for them only to have it be rejected. It's not clear that they're actually willing to merge keyboard selection in *any* form, only that they're not going to merge it in this form. The vague statement that it should be done in VTE coupled with the refusal to give more details than that is a bad sign. It indicates to me that there's no solution they would be happy with, because they cannot describe what they want.

**Comment by Corwind** [comment]
I've made a little script to install termite on a fresh Ubuntu installation. It works on my machine, on which I installed Ubuntu 2 hours ago. It _should_ work on any Ubuntu-based distribution but please let me know if there is a problem.

https://github.com/Corwind/termite-install/blob/master/termite-install.sh

**Comment by blacksky86** [comment]
@Corwind Thank you for the script, however it didn't work out for me by simply running it. I kept on getting permission errors for some reason, even after running as sudo. The solution was to simply do each step on its own line and waiting a little longer. Worked on my Linux Mint 17.2, 64 bit. 

On a side note, I am not getting color the correct colors and don't mean to highjack the thread, but might be related to a dependency? My colors for outputting the files and directories do work on Terminator but don't seem to work on Termite. Little overlap from this other issue [No right color](https://github.com/alpha-omega/termite-colors-solarized/issues/1) 

Terminator
![terminator](https://cloud.githubusercontent.com/assets/3500392/9254316/be574a30-4197-11e5-8d86-f71f97a40abb.png)

Termite
![termite](https://cloud.githubusercontent.com/assets/3500392/9254328/cccf457c-4197-11e5-91cb-39f5ea7b9982.png)
