### ISSUE TITLE
Unneeded spacing at the bottom of the terminal

### ISSUE THREAD

**Issue by Brottweiler** [thestinger/termite#174]
Comparing RXVT-Unicode and Termite, there is a spacing at the bottom of Termite. Like this:

Termite:
![](http://i.imgur.com/0gSfwCT.png)

RXVT-Unicode:
![](http://i.imgur.com/KEPKGPa.png)

How do I remove this spacing, or is it "hardcoded"? Why is it there?

**Comment by og01** [comment]
I am seeing this as well, I have highlighted the issue in this image:

![highlight](https://cloud.githubusercontent.com/assets/184906/9231445/29c9ffec-4120-11e5-859f-df27957e28f4.png)

I purposefully selected all the text in the window to highlight where the extra space (dark green) is along the right and bottom of the window.

I have enabled size_hints. If I resize the window it resizes in character sized increments as you should expect, and the extra space remains the same size, as if the window were just too large in these dimensions.

**Comment by og01** [comment]
Another update to this, I have some wide characters in my font, and the extra space to the right seems to line up perfectly if I put one of these wide characters in the right most column, which sort of explains that.

Not really sure about the extra space at the bottom though.

**Comment by Narrat** [comment]
Got the same "issue", whith this "dead" space.
size_hints is enabled.
Example with cdw:

![termite_cdw](https://cloud.githubusercontent.com/assets/2787518/9332875/207c1ca8-45c7-11e5-84f7-983ee4fc8451.png)

Those bars appear on every occasion (started with or without geometry option) and are best recognized with ncurses programs, like cdw or vifm (at least for me)

**Comment by kj** [comment]
I was seeing this too. I couldn't use `size_hints`, so I had to find the "correct" pixel geometry, which always seemed to be a multiple of the font size + 2 pixels (as in the patch above). Setting the padding for `VteTerminal` to zero (as in the README) fixed this and allowed me to use `size_hints`, so I guess the widget has a default padding of 1px, at least in my environment (I'm running Gnome if it makes any difference). Can the calculated geometry when using `size_hints` take the widget's padding into account?

**Comment by og01** [comment]
To confirm what kj just said, adding the following to my `~/.config/gtk-3.0/gtk.css` file fixed this issue for me:

    VteTerminal {
        padding: 0px;
    }

I guess I should have rtfm!

**Comment by Brottweiler** [comment]
:+1: @og01 and @kj 

Should this be closed as resolved then?

**Comment by saivert** [comment]
No, I don't think so. An application should not require specific configuration in widgets to work as intended. Code needs to factor in the padding or programatically set this to zero for the widget instance.

**Comment by thestinger** [comment]
Setting padding to 0 will also remove the padding from around the other edges. It might work around this problem but I don't think it's the root cause or a real solution.

**Comment by thestinger** [comment]
I'm not entirely clear on what the issue being reported here is. It's a cell-based program so only a multiple of the cell size is going to be non-dead space. If it doesn't use size hints, it has to cope with the dead space itself by filling it in. If it does use size hints, then it's up to the window manager if it respects them (otherwise it's the same as without them). The cdw screenshot looks like size hints working as intended, the window manager is just filling in the space *around the window* with a different fill colour.

VTE does use some padding around the edges by default, and CSS is the right way to disable that. It's not just adding that padding at the bottom though, it does it all the way around the edges. By default, it uses 1px of padding for me but it depends on the GTK theme.

**Comment by saivert** [comment]
Sure, the window manager is responsible for following the size hints but this is a standard X11 thing and most window managers follow it except for tiled wms where it doesn't make sense. My hack adds 2 pixels to both horizontal and vertical size_hints which fixes the problem. This ensures that the window resizes in steps that fit the VTE widget exactly and doesn't leave any leftover space. Because of the apparent 2px default padding of the VTE widget the container window doesn't have enough space for it using current size hints so you will always have leftover space in the bottom and to the left of the VTE widget regardless of window size. I'm not sure if it is the VTE widget refusing to fit in the window or if the leftover space is actually inside the VTE widget where it just doesn't render any text cells because they would be truncated otherwise. I need to study the code more.

**Comment by thestinger** [comment]
The issue might be that we're not properly including the padding in our code.

**Comment by Narrat** [comment]
Just to make it clear with the cdw screenshot.
Using another vte based terminal (in this case roxterm (since 3.x on vte3)) there isn't this spacing. And a difference in size, although they get the same geometry parameter (doing it in the "classical" geometry), and the same font + font-size
https://paste.archlinux.de/qVAVC/
top left: starting commands
black background in cdw => roxterm
grey background => termite

In this conestellation the termite window is larger then the roxterm one (and the larger part is the unneeded spacing). If I let them completly overlap this also applies for the the black spacing to the right.
Checking the size (xwininfo), the wm tells me, they're the same geometry (although actual height and width is different)

**Comment by thestinger** [comment]
Okay, so this is just a bug with how the size hints are set. Fixing it now.

**Comment by romariolopezc** [comment]
![image](https://user-images.githubusercontent.com/6199588/72533406-bb4f0c80-383a-11ea-8565-2000b2a5e176.png)

I'm seeing the same space, as you can see in the image. Modifying the line height seems to decrease the size of the bottom space.

Setting the margin-bottom to -10px seems to work but space is eaten. I can't use -8px because it doesn't work as expected

![image](https://user-images.githubusercontent.com/6199588/72533542-f81b0380-383a-11ea-8b09-8f64587b139e.png)
