### ISSUE TITLE
Consider using terminal-colors.d

### ISSUE THREAD

**Issue by Earnestly** [thestinger/termite#206]
util-linux [recently](http://karelzak.blogspot.co.uk/2014/04/terminal-colorsd.html) added a defacto standard location for defining colours such as for `dmesg` and `fdisk`.

Although termite is perhaps a little out of scope as its really only meant to be used with ANSI colour escape sequences, I did wonder if termite might be able to reuse this location regardless.

The reason for this is mostly to split colour definitions out of the config, either this or the ability to `#include` config snippets.

**Comment by Ploppz** [comment]
I came here to ask for that. I would like to separate colours from the general configuration, so that I can easily switch between colour schemes without having to worry about keeping all other configuration the same across these colour schemes. So at least an `#include` mechanism would be very helpful.

I see this was posted some months ago. What are the chances that someone will consider this?

**Comment by thestinger** [comment]
I don't think this would be a good fit, because as you mentioned it's not intended for defining a 256-color palette with up to 32-bit color definitions.
