### ISSUE TITLE
Using old commits of termite

### ISSUE THREAD

**Issue by esn89** [thestinger/termite#208]
Since the newest termite seemed to have the "image-preview-feature-broken" in ranger, I decided to try the older commits of termite.

I cloned the repo in arch, and looked up 'git log':
http://i.imgur.com/wV7VcfV.png

And picked a commit from a date I knew that the termite image preview feature worked in ranger.  I tried the one here beginning with "be4..."

I ran make and make install and while that installed successfully, I started termite, and noticed that whenever I started typing into the termite terminal, the characters would repeat.

ssuuuddoo ppaaacaaccmaaan  is what I will see, if I simply typed "sudo pacman".

Could this be because the older commits don't play well with the newer vte-common of 0.38.3-1

**Comment by thestinger** [comment]
It doesn't work because the window has 32-bit color depth instead of 24-bit. This is a consequence of having strong support for transparency where any color in the theme can be given an alpha channel. I could add in some kind of hack to avoid adding an alpha channel when it's not used by the theme... but I don't really want to. The hack used by w3m to overlay images is just plain broken. If you remove the lines calling `on_alpha_screen_changed` and installing it as an event handler the problem will be "fixed".

There's nothing I can do about older commits not working anymore...
