### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by raffomania** [thestinger/termite#226]
I'd like to set a background image for my terminal (you might also call it pseudo transparency).
I found #139, which says that upstream doesn't support either true transparency or background images.
Nevertheless, nowadays true transparency seems to be supported, so is there a chance to get a config option for background images, too?

**Comment by thestinger** [comment]
Upstream deprecated (and then removed) support for true transparency, pseudo transparency and background images. Support for true transparency came back because the VTE widget was properly migrated to the RGBA color model so alpha channels can be specified for each color in the theme. I don't want to maintain a larger out-of-tree patch for VTE so you're going to have to take it up with upstream if you want it back. I will add a configure option for it if VTE supports it again. I wouldn't expect that to happen though.
