### ISSUE TITLE
How to compile termite on Mint Rebecca (17.04) based on Ubuntu 14.04

### ISSUE THREAD

**Issue by SRGOM** [thestinger/termite#230]
I get the following error
    termite.cc:31:22: fatal error: gdk/gdkx.h: No such file or directory

I've installed gtk related pacakges that looked related from `aptitude search`. What package is expected to contain gdk/gdkx.h?

**Comment by thestinger** [comment]
On Debian-based distributions you need `-dev` packages for headers because they split them out for insignificant disk space savings.

**Comment by Earnestly** [comment]
Also Fedora-like distributions.  It's a very annoying practice but at least there you can `dnf install /usr/include/gtk/gdkx.h`

**Comment by SRGOM** [comment]
Ooh well, I cheated- I should have correctly noted that I'm using Mint. I have some package mismatch that's preventing the installation. In any case, would you guys consider providing a statically linked library for i386 and x64 on bitbucket? A lot of people want to try termite but very few manage to because of the extra compilation step.

**Comment by thestinger** [comment]
AFAIK, building it on Mint won't be any different than building it on Ubuntu or Debian.

I'm not interested in making and hosting builds. I would package it in the Arch repositories if vanilla VTE ever gained the necessary APIs, but that's it. I don't intend to do much more than fixing bugs and making small improvements now and then. It works well for me and that's what counts, because it's not a very interesting project to work on and I wouldn't get anything back from doing more.

**Comment by SRGOM** [comment]
I understand. Thanks for taking the time to answer... If I manage to do a static build, I will post a link here.
