### ISSUE TITLE
Repeating characters

### ISSUE THREAD

**Issue by hari-rangarajan** [thestinger/termite#238]
I installed it using the script below. Typing "Hello" produces "hhehellllllo" I'm using awesome wm as my tiling manager.

git clone --recursive https://github.com/thestinger/termite.git
git clone https://github.com/thestinger/vte-ng.git
sudo apt-get install g++ libgtk-3-dev gtk-doc-tools gnutls-bin valac
sudo apt-get install libglib3.0-cil-dev libgnutls28-dev libgirepository1.0-dev
sudo apt-get install libxml2-utils gperf
cd vte-ng && ./autogen.sh && make && sudo make install
cd ../termite && make && sudo make install
sudo desktop-file-install termite.desktop
sudo cp /usr/local/lib/libvte-2.91.a /usr/local/lib/libvte-2.91.la \
	/usr/local/lib/libvte-2.91.so /usr/local/lib/libvte-2.91.so.0 \
	/usr/local/lib/libvte-2.91.so.0.4000.2 /usr/lib

**Comment by hari-rangarajan** [comment]
https://github.com/thestinger/termite/issues/208

I tried disabling the alpha callback mentioned. That still doesn't solve the repeating characters problem.

**Comment by thestinger** [comment]
It has nothing to do with the color depth issue in #208. For the record, that's not a bug in Termite or the libraries it uses. The hack used by w3m to overlay images is just broken and working around it isn't a priority.

It's probably not working properly because you installed it to `/usr/local` instead of `/usr` and your distribution doesn't support extending the terminfo database in `/usr/local`. You need to install the terminfo file by running `tic -x termite.terminfo` as root.
