### ISSUE TITLE
Problem to use vim like "termite -e vim"

### ISSUE THREAD

**Issue by inkn** [thestinger/termite#246]
when i edit file in file manager like "termite -e vim .config/termite/config",the vim always open a new file with no file name.How to solve this, is it my config problem?

**Comment by thestinger** [comment]
You're passing `.config/termite/config` as an argument to Termite. You need to pass the command as a single argument to `-e` like `-e 'vim filename'`.

**Comment by svenstaro** [comment]
In @inkn's defence, this is how it works ok in xterm, though. I agree that termite does it more cleanly, though in some cases this results in incompatibilities.

**Comment by that1communist** [comment]
This is the only thing preventing me from using this terminal, is there any way we can have an alternative to the -e that allows me to do things like exec termite -e ncmpcpp in my i3wm config? Currently it just immediately closes.

Furthermore I can't use neovim as an editor with this terminal, because I can't make a .desktop file that opens nvim in a termite window.

This seems like a pretty major oversight in an otherwise fantastic terminal.

**Comment by BurningTreeC** [comment]
@that1communist I'm using termite with i3. in your config, just write **exec termite -e "ncmpcpp"** and it should work. The quotes should solve the issue

**Comment by that1communist** [comment]
Termite -e "vim" opens a blank window Everytime, I will try the vim -c when I get up. Ncmpcpp was my bad.

**Comment by arnthorla** [comment]
I was having issues in i3 when wanted to open config files with a keypress. When I used relative path it always opend my vim editor on a blank file with a message of New Directory or something along those lines. However when I used an absolute path it worked as expected. 

Ex.
`bindsym $mod+ctrl+1 exec termite -e "vim /home/yourusername/.config/i3/config"`
