### ISSUE TITLE
Read config from xresources

### ISSUE THREAD

**Issue by eigengrau** [thestinger/termite#263]
As a possible enhancement, it would be great if some configuration, most notably the color definitions, could be read from the X resources database. This would allow keeping the color scheme in sync between termite and other applications (since Xresources support CPP `#define` statements for global color definitions, which can then be assigned to several attributes).

An alternative implementation might go along the lines of #43 resp. #260. However, while an include directive would help reduce duplication between theme-specific termite config files, one would still need to dynamically create the config files on the fly if one wants to have global color definitions shared between applications.

**Comment by thestinger** [comment]
I don't want to support the legacy X resources database. It's an obsolete feature and it isn't present in Wayland where Termite runs as a native application. The only current X11-specific code is [setting the `WINDOWID` environment variable](https://github.com/thestinger/termite/blob/b10a5f2fac65d62fc3c8c8071b558a14dd8550ce/termite.cc#L1604-L1615) to make Vim happy.

It would make sense to obtain the defaults from the GTK theme, but Termite requires more values than it's going to have for terminals since it has things like URL hints.
