### ISSUE TITLE
urls must have http:// prefix to be matched?

### ISSUE THREAD

**Issue by Dieterbe** [thestinger/termite#265]
i notice that often urls are simply like "www.dns.be" or "google.com" and such.
however the url hints mode only recognizes urls that start with "http://" :'(

**Comment by thestinger** [comment]
It might make sense to try matching raw domains, but it would result in a *lot* of false positives. Anything with a dot in it is a valid domain. It might be better to simply make the URL regexp configurable but it's a pretty complex regexp.

**Comment by Earnestly** [comment]
Generally at this level termite doesn't need to do essentially url validation, it must merely try to approximate what humans expect, url validation is then done where ever they may be passed instead.  Although not requiring a scheme feels a little wrong to me, mostly due to the incredible amount of false positives that can generate.  I mean, by approximation you want some degree of flexability but not requiring the scheme feels like that's too far.

**Comment by miseran** [comment]
If matching urls without http:// introduces too many false positives, would it at least be possible to allow opening them with 'o' or 'return' after manual selection? Currently, even this doesn't work.

**Comment by Earnestly** [comment]
You can select text in visual-mode and press `o` to open it with your browser, same for `Return` but it also returns you to insert-mode.

**Comment by miseran** [comment]
My bad, it didn't work before because I had xdg-open set as the browser.

**Comment by thestinger** [comment]
I don't want to change this.
