### ISSUE TITLE
how about 'yy' in selection mode?

### ISSUE THREAD

**Issue by Dieterbe** [thestinger/termite#266]
yy to copy the entire line, just like in vim. would be nice. thanks :)
btw I love termite ! it has all the power features i was looking for. (well, almost all)

**Comment by Dieterbe** [comment]
also `y$` (yank til end of line) would be nice

**Comment by thestinger** [comment]
At the moment the keybinding handling is quite dumb and doesn't support combinations of keys (like `less`). It would be easy enough to start adding it, so `yy` wouldn't be hard. Supporting combinations of actions and movements like `y$` should really be done via a proper abstraction rather than hard-wiring each one though. Going to require a fair bit of redesigning how it handles keybinds.

**Comment by schoettl** [comment]
@Dieterbe for now you can use `Vy` - `V` selects the full line.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
