### ISSUE TITLE
Tags.

### ISSUE THREAD

**Issue by hurricanehrndz** [thestinger/termite#296]
Is there any reason why v is used as prefix for verison numbers? Is this something that can be modified?

**Comment by thestinger** [comment]
It was an arbitrary choice for the first tag and the newer tags are kept consistent since there's code relying on that like the Arch Linux packages. Is there any reason it's a problem? A bunch of new tags could be added without the prefix but I don't really see the point. It would clutter the repository unless the existing tags were deleted, and that might break someone's setup.

**Comment by hurricanehrndz** [comment]
@thestinger 

I'm trying to have an automated build for Debian, unfortunately obs does not play well with tags prefix with v at the moment. There are pull request to get this address, but it will be sometime before they get merged. If there is enough interest I could package termite for other distros. Right now I'm just really doing this for myself. 

Anyhow, you can find my work as of now here:
https://build.opensuse.org/package/show/home:hurricanehernandez/termite

I can setup obs  to automatically build termite on new commits to git. When doing git builds I can remove all user intervention in the build as long as the source repository is setup correctly. Version for the packages can bet set to be the latest TAG plus how many commits have occurred from that TAG. Since I can not use the current Tags, I have been forced to somewhat hard code the version.

**Comment by hurricanehrndz** [comment]
Here is the download instructions:
https://software.opensuse.org/download.html?project=home%3Ahurricanehernandez&package=termite
