### ISSUE TITLE
More command line options

### ISSUE THREAD

**Issue by FilipBB** [thestinger/termite#354]
I would like to specify colors on the command line, to override the config file colors, so I can have a dropdown termite window that is semi-transparent and keep other termite windows opaque. It could be done with multiple config files, but a command line option would be more convenient.

**Comment by jelly** [comment]
I don't see how this can be convenient since for a basic change we have to add 15 color options.

**Comment by thestinger** [comment]
Passing a list of colors via a single switch would be possible but not really any more convenient than a configuration file. I think it's too much to pass via a switch. Not sure though.

**Comment by thestinger** [comment]
And if it's via a single switch, then you'll have to include ALL of the colors, at least up to the last one you want to change.

**Comment by thestinger** [comment]
(there are also more than 16 configurable colors: there are 256, along with various miscellaneous ones - it is way too many to have as independent switches)

**Comment by FilipBB** [comment]
Ok, I was thinking more like how urxvt has foreground/background color options, but really all I want to do is specify transparency on the when launching. Would a single switch for transparency be possible?

**Comment by thestinger** [comment]
No, it's part of the color.

**Comment by FilipBB** [comment]
In my config file, in the color section I have some options set:

foreground      = #d8d8d8
foreground_bold = #d8d8d8
cursor          = #d8d8d8
background = rgba(24, 24, 24, 0.92)

and then the rest of the colors are defined to get a specific colorscheme. Now maybe I'm not understanding how this works, but I know that transparency is set as the last field of the rgba color. Would it not be possible to override this with a commandline option?

**Comment by thestinger** [comment]
There aren't going to be CLI switches for setting individual colors, and especially *channels* of individual colors.

**Comment by serussell** [comment]
@thestinger Awwww, please?  Just background?  That's the really useful one.

Here's my use case: in most cases, I want the transparency to be 85% so the background isn't *too* distracting.  So, like @FilipBB, I have something like this in my config:

```
background = rgba(29, 31, 33, 0.85)
```

Sometimes, though, I have some terminal applications where I want the background to dominate; [Cava](https://github.com/karlstav/cava) for instance.  What I'm doing now is editing `.config/termite/config` and changing the alpha to `0.0`, running a terminal for Cava, then changing it back.  It's not hard, but it isn't exactly easy either, and it'd be greatly facilitated by the ability to change the background alpha with a switch.  The least specific solution would be a `--background` flag, which takes a usual config file string.  

I can't get what I want with `compton-trans` because I have a rule that changes the `compton` transparency dynamically and overrides any manual setting; it does **not**, however, screw with the transparency set in the `termite/config` file.

Anyway, that's what I'm trying to do with it, and why it'd be useful for me.
