### ISSUE TITLE
terminfo issue

### ISSUE THREAD

**Issue by alvesadrian** [thestinger/termite#364]
Cannot find terminfo entry for 'xterm-termite'.
am getting that error over ssh into a debian server trying to reattach into a screen session, am using termite from git

**Comment by polyzen** [comment]
You have to install the terminfo on the remote machine. I'd be very surprised if you can't find the solution to this problem with a search.

**Comment by wsdjeg** [comment]
@alvesadrian see here, for me, I just install two package.
```
✔ wsdjeg:JavaUnit.vim [ master | ✔  ] ➭ pacman -Ss termite
community/termite 11-3 [installed]
    A simple VTE-based terminal
community/termite-terminfo 11-3 [installed]
    Terminfo for Termite, a simple VTE-based terminal
```

**Comment by jelly** [comment]
Not a bug.

**Comment by adrian-gluu** [comment]
there isnt any terminfo pkg available in remote host or even in debian also tested both pkgs from arch termite-terminfo and termite and happens the same thing

**Comment by thestinger** [comment]
So take the terminfo file and install it with `tic -x termite.terminfo` there.

**Comment by j-degreef** [comment]
This solved my "cannot find terminfo entry for 'xterm-termite'." problem too.
Why this info is not in the documentation ?

**Comment by thestinger** [comment]
Lack of interest in providing free support and writing documentation for people. It's a common cross-terminal issue. There are plenty of others that we could document too, but Termite isn't particularly actively developed. I work on much more interesting software and earn money for doing so, and I could be writing documentation for paying customers instead of responding to endless complaints about the same stuff here or trying to include it in documentation that many people are not going to read anyway before asking.
