### ISSUE TITLE
Open termite in current directory / Set termite as default terminal

### ISSUE THREAD

**Issue by leninberg** [thestinger/termite#377]
When I use the key combination for i3wm, it works
mod+enter ---> opens termite, as it is specified in i3 config file

But, right-click on a folder -> "open terminal here" (from thunar), opens xterm not termite

I tried changing default terminal with this
sudo update-alternatives –config x-terminal-emulator

but termite wasn't an option

Can you give me any advice?
Thanks

**Comment by thestinger** [comment]
You're asking for advice about Thunar, not Termite. The specific terminal that you're trying to switch it to using doesn't matter, changing it would be the same. Maybe it respects TERMINAL.

**Comment by leninberg** [comment]
Thanks for your prompt reply. do you know why termite doesn't appear as an option when I execute sudo update-alternatives –config x-terminal-emulator? Regards

**Comment by thestinger** [comment]
I don't know about Debian-specific configuration.

**Comment by johnmendonca** [comment]
@leninberg

This happens because you've installed the program manually and not through the package manager, here is how to add it manually:
```
sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/termite 100
```

If you ever delete the program you'll need to remove the alternative manually:
```
sudo update-alternatives --remove x-terminal-emulator /usr/local/bin/termite
```

After adding the alternative you still need to select it:
```
sudo update-alternatives --config x-terminal-emulator
```

More info here:
https://askubuntu.com/questions/81166/how-do-i-get-an-application-to-appear-as-a-choice-in-update-alternatives

**Comment by leninberg** [comment]
@johnmendonca 
I no longer have that virtual machine, but I will recreate it and use your info.
Thank you very much for the help!
