### ISSUE TITLE
Cannot open libvte-2.90.so.0

### ISSUE THREAD

**Issue by Marcel-Robitaille** [thestinger/termite#398]
I have just compiled termite. When I try to run it, I get this error:
```
termite: error while loading shared libraries: libvte-2.91.so.0: cannot open shared object file: No such file or directory
```
However, I have libvte:
```
$ sudo apt install libvte9
sudo: unable to resolve host DESKTOP-L1D0IQ8
Reading package lists... Done
Building dependency tree
Reading state information... Done
libvte9 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
```

I am on bash on ubuntu on windows.

**Comment by jelly** [comment]
This is not a termite bug, you've configured something wrong on your system.

Check to fix your LD_PRELOAD, for example if vte3-ng is installed in /usr/local

LD_PRELOAD=/usr/loca/lib/ termite

**Comment by Marcel-Robitaille** [comment]
Thanks, that seems to have worked. Now I am getting this issue for which I think xming is responsable:
```
LD_PRELOAD=/usr/loca/lib/ termite
ERROR: ld.so: object '/usr/loca/lib/' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

** (termite:215): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[1]    215 abort (core dumped)  LD_PRELOAD=/usr/loca/lib/ termite
```

**Comment by b33rcity** [comment]
Sorry to reopen an old issue. I'm getting the same error message but only when trying to run termite as a non-root user. I'm pretty sure this is because I compiled and installed everything as root. If I use `sudo termite` or `su` to root and then `termite`, I can open termite (an error message gets printed; seperate issue, though). 

LD_LIBRARY_PATH is set in /etc/environment to include the dir where vte and related libraries are installed, and every dir in the path down has r-x set for all users and root:root ownership (which is normal for stuff under /usr, right?). 

I'm hoping there's some permission or ownership I can change somewhere rather than go through and recompile the whole thing as the non-root user?
