### ISSUE TITLE
Disable Ctrl-Tab

### ISSUE THREAD

**Issue by GoodiesHQ** [thestinger/termite#464]
Short of re-compiling after commenting out, [Line 959](https://github.com/thestinger/termite/blob/master/termite.cc#L959) (and returning FALSE immediately after), how can I disable scrollback completion? I'm trying to map ctrl-Tab in my vimrc, but I cannot do so without popping up this mini dialog.

**Comment by egmontkob** [comment]
Not sure how to do that in Termite (other than altering the source), but even if you managed to do that you'd face a bigger problem. Namely that VTE (the terminal emulator widget behind Termite), just like every other terminal emulator I'm aware of, ignores the Ctrl modifier for the Tab key, that is, emits a simple Tab character rather than something different. As such, there's no way to recognize Ctrl-Tab in Vim.

**Comment by thestinger** [comment]
The binding was intentionally chosen to be something that can't be different than tab right now, like the others. There are some standard VTE bindings overlapping with stuff that could be used if it wasn't intercepted but I tried to avoid that for any of the CopperheadOS bindings.

**Comment by thestinger** [comment]
Er, I mean Termite. You can tell where my brain is focused these days...
