### ISSUE TITLE
Links are not opened properly

### ISSUE THREAD

**Issue by lillemets** [thestinger/termite#472]
I use *rtv* to browse Reddit and open links included in comments in browser. Reddit comments are composed in markdown so the links are shown like this `[description](http://www.link.com).`. Termite recognizes these links, but not as `http://www.link.com` but as `http://www.link.com).`. So Termite doesn't allow me to open these links simply by clicking on them as that opens `http://www.link.com).` in my browser. What I wish is Termite to recognize that the `).` is not part of links.

**Comment by egmontkob** [comment]
Just FYI: `gnome-terminal` works the way you expect, but recently someone at https://askubuntu.com/questions/895710/gnome-terminal-highlight-urls-ending-in-close-paren/895813 complained about it and asked for a more `termite`-like behavior. There's no clear good solution, or at least not an easy one :(

**Comment by thestinger** [comment]
This is how it's intended to work right now. The URL regex could be improved, but no one has shown interest in doing that. It would be possible to use a hack for matching *wrapping* parentheses but there's no way we're going to stop recognising ( and ) in URLs in general because they are among the explicitly permitted characters.

**Comment by egmontkob** [comment]
Just FYI: I've ended up addressing this in `gnome-terminal` so that it allows only balanced pairs of parentheses in URLs, using regex recursion. That is, in `https://en.wikipedia.org/wiki/The_Offspring_(album)` the trailing `)` is part of the URL, whereas in `[description](http://www.link.com).` it is not.
