### ISSUE TITLE
terminal colors showing at sides in vim

### ISSUE THREAD

**Issue by Sleepful** [thestinger/termite#514]
http://imgur.com/a/wXWEW

Terminal has solarized-light colors and vim has solarized-dark colors, as you can see, for some reason vim isn't covering the whole terminal window and the sides are showing the terminal's background

**Comment by jearbear** [comment]
I think this is a common issue with all terminal emulators since vim will color the background to the nearest character only. Unfortunately it's a bit unavoidable when using tiling WMs which is why I think a lot of terminals will resize to the nearest characters only when in floating mode.

Reference: https://stackoverflow.com/questions/26937521/how-make-vim-fill-terminal-window

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
