### ISSUE TITLE
Is it possible directly display image in the terminal without opening a new window?

### ISSUE THREAD

**Issue by TommyJerryMairo** [thestinger/termite#539]
Like this one:

![example](https://i.stack.imgur.com/A5mDK.png)

**Comment by jelly** [comment]
I believe that requires sixel report, what terminal is this even?

**Comment by egmontkob** [comment]
And what `ls` command?

(I _guess_ it's just a mockup based on `gnome-terminal`, created in `gimp` or something similar.)

**Comment by egmontkob** [comment]
See [GNOME bug 729204](https://bugzilla.gnome.org/show_bug.cgi?id=729204) (and follow the links from there for additional information) for the status of sixel support in VTE. There's a patch which I haven't tried, but based on the discussions there, I'm not super keen on adding graphics support to VTE. It might end up landing there, though. But then it'd still need a corresponding variant of `ls`.

Several terminal emulators (including [terminology](https://www.enlightenment.org/about-terminology) and [kitty](https://github.com/kovidgoyal/kitty/blob/master/graphics-protocol.asciidoc)) have also implemented their own graphics format, along with corresponding tools (e.g. `tyls`).

Alas no standard seems to emerge that doesn't suck big time (sixel is so last millennium that it hurts), probably due to the model/view split mentioned/linked from the aforementioned bug it just cannot be done right.

Particularly for `ls`, there's something to consider:

Newest VTE versions support explicit hyperlinks (#476), and so does the latest version of `coreutils`'s `ls`. It outputs the filenames as usual, but each of them are hyperlinked to the corresponding file.

On top of this, `termite` could show a preview of the given file on mouseover (khm, I mean some keyboard shortcuts). `gnome-terminal` has a [proof of concept patch](https://bugzilla.gnome.org/show_bug.cgi?id=779734#c123) (that is: working, but not ready for mainstream inclusion) for this. Maybe `termite` could implement it properly. (Of course I understand it's pretty different from what the original reporter wishes to have, but this one is at least reasonably doable.)

**Comment by lowfatcomputing** [comment]
@egmontkob possibly an alias to [lsix](https://github.com/hackerb9/lsix). I was using it in termite with [the experimental sixel support](https://github.com/saitoha/vte-sixel) before the vte/vte-ng split.

**Comment by egmontkob** [comment]
@lowfatcomputing Thanks for pointing me to `lsix`, I've never heard of it.

(By the way I still think the above screenshot is a mockup. The font is the same as the terminal's, yet not aligned vertically to the character cells of the prompt, and not aligned nicely to the pictures either. Plus the files aren't in alphabetical order... It's pretty irrelevant for the feature request though.)

**Comment by robin-a-meade** [comment]
The mockup is from here: https://askubuntu.com/q/97542

**Comment by dtzWill** [comment]
The vte-ng patches are minor and can be applied pretty easily, it turns out.

If you'd like, you can try building with my fork: [vte-sixel-ng](https://github.com/dtzWill/vte-sixel-ng) which worked well enough in daily use for.. actually exactly 1 month today! Ha! :).

I'm actually moving away from it since I didn't find many uses.  But it's neat! :+1:

FWIW my fork also rips out the "reaper" kludge which was causing problems on my platform.  On glibc-linux removing it also fixes the source of this fun error/warning:

```
(termite:27242): GLib-WARNING **: GChildWatchSource: Exit status of a child process was requested but ECHILD was received by waitpid(). Most likely the process is ignoring SIGCHLD, or some other thread is invoking waitpid() with a nonpositive first argument; either behavior can break applications that use g_child_watch_add()/g_spawn_sync() either directly or indirectly.
```

Anyway just heads-up so no one feels I snuck it in there :).

--------------

While I'm showcasing my patch rebasing skills :laughing: here's a branch applying the ng patches to 0.51.3: https://github.com/dtzWill/vte-sixel-ng/tree/0.51.3-ng

GLHF! Apologies if anything breaks, use at your own risk, etc.

**Comment by jelly** [comment]
Cool, it would be nice if VTE merged this, as I'm becoming less and less interested in maintaining vte-ng.

**Comment by bestouff** [comment]
> (By the way I still think the above screenshot is a mockup. The font is the same as the terminal's, yet not aligned vertically to the character cells of the prompt, and not aligned nicely to the pictures either. Plus the files aren't in alphabetical order... It's pretty irrelevant for the feature request though.)  

I rather think it's directly from MacOS's [Iterm2](https://www.iterm2.com) terminal emulator which has great image support, see protocol documentation here: https://www.iterm2.com/documentation-images.html (as well as many other more or less useful [proprietary escape codes](https://www.iterm2.com/documentation-escape-codes.html)).

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
