### ISSUE TITLE
erratic insertion of a NO-BREAK-SPACE in commands

### ISSUE THREAD

**Issue by evanescente-ondine** [thestinger/termite#542]
I've found a rather disturbing and **erratic** misbehavior.
**Sometime**, but not always, termite (what else ? Not the shell, I've verified), in commands like this
`cat "message pour reddit" | grep ici`
inserts a NO-BREAK-SPACE character seemingly between the vertical bar (for redirection) and the next command of the pipe. Which gives that message:
```
cat "message pour reddit" |[# 194][# 160]grep ici;
                                             ^ ' grep' command not found

``` 
I reboot, and it worked. I must add this is as French keyboard... Maybe it's X and not Termite ?

**Comment by egmontkob** [comment]
It seems to me that the pipe symbol is on AltGr+6 on the French layout, correct?

Could this be that AltGr+Space produces the non-breaking space, and you keep holding AltGr while typing that space?

**Comment by evanescente-ondine** [comment]
God, no, you found. Ahah, you're right ! Ah, it makes laugh so much I can almost forget how much a pain in the ass it was ! Thanks, my lord !

**Comment by egmontkob** [comment]
Might be worth it reporting to the maintainers of the keymap definition, I think the given behavior sucks for the exact same issue that you ran into.

For the record, I cannot reproduce this on Ubuntu Artful, X11. After a "setxkbmap fr" AltGr+Space produces a regular space for me. Maybe you have an older X11 and it's been fixed since. Maybe Ubuntu has a patch that fixes it, or your distro has one that breaks it. Maybe you have Wayland, which... wait, does it ship its own keymap definition or does it reuse X11's? I don't know...
