### ISSUE TITLE
Gtk scrollbar position not correctly updated when using Page-up/down

### ISSUE THREAD

**Issue by anthraxx** [thestinger/termite#559]
When scrolling with `shift+page-up/down` the scrollbar is not always adjusted accordingly.

Way to reproduce:
`Up, Up, Down`

Result:
`Up, Up, Up` While the page's text actually scrolls down in the 3th call. When doing another `Down` then the scrollbar does a big jumps to the correct position.

**Comment by egmontkob** [comment]
The upstream issue is https://bugzilla.gnome.org/show_bug.cgi?id=771899.

Any help is appreciated, we're completely puzzled, we aren't even sure yet whether it's a bug in GTK+ or VTE.

There's a workaround for gnome-terminal attached there, Termite could also apply a similar workaround until the real issue is located and fixed.

**Comment by egmontkob** [comment]
@anthraxx There's a candidate vte patch in comment 32 of the aforementioned bug, I'd appreciate if you could test that (apply against vte-ng) and report back whether you encounter any problems.

**Comment by egmontkob** [comment]
It's now fixed upstream, will appear in vte-0.52.0. We might even backport it to 0.50.3 but I cannot promise this.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
