### ISSUE TITLE
Use ncurses upstream terminfo?

### ISSUE THREAD

**Issue by kyrias** [thestinger/termite#566]
ncurses 6.1 has apparently added a terminfo file for termite, named "termite" there (as it rightfully should be).  It would probably be a good idea to migrate over to that, so that it'll end up being widely available without requiring a second installed package everywhere.

**Comment by veox** [comment]
For reference, the `termite` entry in `ncurses` is available [since version 6.1](http://invisible-island.net/ncurses/NEWS.html#index-t20180127) - or, more precisely, [the pre-release from 2018-01-21](http://invisible-island.net/ncurses/NEWS.html#index-t20180121).

Many distributions with a slower release cycle don't yet have this version of `ncurses`, so will still need the manual procedure, as currently.

Cc: @Sweenu

**Comment by lifranc** [comment]
There's slow, and then there's *slooooooow* ...

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
