### ISSUE TITLE
Block cursor's unfocused height larger than line height

### ISSUE THREAD

**Issue by ghost** [thestinger/termite#573]
It seems like the block cursor's unfocused height is bigger than termite's line height by about 2 pixels (1px top and 1px bottom).

Images for reference (the block cursor is on the right):

![Focused](https://i.imgur.com/6E7apJC.png)

![Unfocused](https://i.imgur.com/pos5W9c.png)

As you can see on the images, the cursor's focused mode does have the same height as the line height, which in this case is 21px. But when it enters unfocused mode, the block's top & bottom expand out of the line by 1 pixel each for the white border, which makes the block cursor's total height to increase to 23px.

Setting the padding in `gtk.css` does not solve the problem; the cursor's top border is cut off instead.

Searching around the project's github, I did found [this comment](https://github.com/thestinger/termite/issues/174#issuecomment-48119184), which (maybe) is the source of this issue?

It's definitely not a big problem, but I just find it absurd: doesn't the block cursor's height have to always be equal to the line height, regardless of the state it's in?

**Comment by egmontkob** [comment]
This is done by VTE, the behavior is hardcoded and intentional. I _guess_ the point is that the letter underneath the cursor should be as readable as possible (even at smaller font sizes), and an outer rectangle serves this purpose better than an inner one.

> doesn't the block cursor's height have to always be equal to the line height

There's no "have to" in this story, it's a matter of taste, VTE developers chose this look a long-long time ago. It wouldn't even have to change the cursor look to an outlined rectangle, it could leave it unchanged on a focus out. There are two more cursor shapes (I-beam and underline) available, they don't change their shape on cursor out. Recently I even experimented with [hiding the cursor on focus out](https://bugzilla.gnome.org/show_bug.cgi?id=789137) to match the behavior of most other apps, but ended up rejecting the idea.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
