### ISSUE TITLE
Resize without geometry option

### ISSUE THREAD

**Issue by p3p1** [thestinger/termite#590]
I don't know why the geometry option has been removed but for me it was really useful. I had different sxhkd keys combination to open terminal windows with different sizes. Without the geometry option which is the best way to launch a terminal window with a predefined size?

**Comment by jelly** [comment]
geometry handling was deprecated in VTE, so it needs to be implemented alternatively if you still want it.

**Comment by jelly** [comment]
I'm fine with supporting it, I just don't have time or motivation to add the feature. PR's are fine.

**Comment by awnumar** [comment]
I had this feature enabled in the launcher command for termite so the update yesterday broke the terminal for me.

I understand that the feature needs to be re-implemented but in the meantime perhaps re-add the `--geometry` flag as an undocumented flag so that termite still launches if the flag is specified.

**Comment by belzebub40k** [comment]
For KDE Plasma users: go to "System Settings -> Window Management -> Window Rules" and add new rule with the desired geometry.

**Comment by thebodzio** [comment]
How about exposing something like “--rows” and “--columns” utilizing vte_terminal_set_size (https://developer.gnome.org/vte/0.48/VteTerminal.html#vte-terminal-set-size)? I realize it is more of a workaround than a solution, but still it could be somewhat useful.

**Comment by thebodzio** [comment]
@belzebub40k Yes, but unlike “geometry”, this allows one to set only the size of the terminal window (well, “terminal widget” to be precise) not its position. And because it is missing an important portion of the original functionality I consider it a workaround, or, at least, “more like a” workaround ;}.

**Comment by belzebub40k** [comment]
Understood. I wasn't aware that you could also change the position. The documentation was only about setting height and width.

**Comment by pigmonkey** [comment]
I too used the geometry option, but just to set the size of a window that I float in i3. Flags for `--rows` and `--columns` would be a good workaround for me.

**Comment by nezumisama** [comment]
:+1: for having an option to set initial size in rows and columns. For a TE I think it makes a lot more sense, since a character position is the basic unit of measurements. When you set number of pixels to not match the fixed character size you get (IMO ugly) empty space on the right and bottom of the window. And you have to either do the math or empirically find the correct number of pixels you need for perfect sizes, and that's each time you want a new size.

**Comment by marnout** [comment]
A work around is to use xdotool  : 
1. create a file, say left, in your $HOME/.local/bin (make sure it is in your path) : 
`cd ~/.local/bin
echo "xdotool getactivewindow windowsize 950 1019" > left
echo "bash" >> left`
2. Change its mode : 
`chmod  +x left`
And now start termite with : 
`termite -e left`
termite will start with width=950 and height=1019

Another work around is to compile a new termite.cc with a new option in th GOptionEntry entries[], and using gtk_widget_set_size_request(GTK_WIDGET(window), width, height); instead of gtk_window_get_size(GTK_WINDOW(window), &width, &height); (line about 1844)

**Comment by anonymous352** [comment]
Another work around is to use devilspie2:

http://git.savannah.gnu.org/cgit/devilspie2.git

**Comment by Barbarossa93** [comment]
@marnout Did you write that main function? Is there a reason why we can't make a PR out of it?

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
