### ISSUE TITLE
Options for mixed-DPI systems (eg heterogeneous monitors)

### ISSUE THREAD

**Issue by cpick** [thestinger/termite#607]
I frequently use a laptop with an external monitor that have very different DPIs.
Ideally I'd like to zoom/scale automatically when moving a window from one screen to another.

Are there any known solutions for this in termite already?  If not any ideas on a good way to implement a feature like this?  I could take a crack at implementing it if pointed in the right direction.

**Comment by ptrxyz** [comment]
Is that really a thing a terminal emulator should handle? To me it looks like it's a general "problem" that every application has to deal with. Termite does what it should, which is rendering stuff with the DPI set for the monitor.

I fI got you right, what you propose is to have termite check for DPI changes _all the time_ and then changes i.e. the font size? How would you then handle cases where a single termite window spans among several monitors with different DPI each?

In my opinion this functionality is nothing termite should handle, I'd rather see it in display server or maybe your WM.

But, if it's just about different DPI: not sure if it helps you, but termite respects the XFT DPI settings. Maybe you can fiddle around with xrdb, and have a different Xft.dpi setting per monitor, _since xrdb uses the C preprocessor (because of course it does)_. See here: https://unix.stackexchange.com/questions/137844/per-screen-font-config

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
