### ISSUE TITLE
Zsh RPROMPT strange behavior on resize (not redrawing correctly)

### ISSUE THREAD

**Issue by Tomaszal** [thestinger/termite#614]
I've been having some problems while tinkering with my zsh prompt and I've narrowed it down to this. Whenever RPROMPT is set the history gets spammed with prompts on resize of the window. It's especially noticeable when you make the window smaller.

+ Here's how it looks normally:
    ```
    PROMPT='%n > '
    ```

    ![normal](https://user-images.githubusercontent.com/23457585/42160574-6b6ec976-7e00-11e8-8f31-af3c7400eda8.gif)

+ Same prompt with long text:

    ![longtext](https://user-images.githubusercontent.com/23457585/42160602-7ee21f80-7e00-11e8-9fa2-fe6c3325e432.gif)

+ Here's how it looks with RPROMPT set:
    ```
    PROMPT='%n > '
    RPROMPT='%D{%H:%M:%S}'
    ```

    ![rprompt](https://user-images.githubusercontent.com/23457585/42160620-87d204b6-7e00-11e8-9a9a-d68fb52f0d16.gif)

**Comment by jelly** [comment]
Same behaviour with gnome-terminal?

**Comment by egmontkob** [comment]
See [VTE 778547](https://bugzilla.gnome.org/show_bug.cgi?id=778547), [VTE 780995](https://bugzilla.gnome.org/show_bug.cgi?id=780995) and #549.

(Long story short: Not a VTE or Termite bug.)

**Comment by egmontkob** [comment]
> However, I still think it could be improved in VTE, as other terminals (xterm, urxvt) are handling it much much better.

xterm doesn't do rewrap on resize. As said in an aforementioned bug, the zsh resizing bug occurs in urxvt too, although less frequently than in VTE.

We've significantly improved VTE's performance recently, although it may still not be there as urxvt's. It's a continuous ongoing effort, and also there are a few bugs about it. However, I'm not particularly interested in making this particular race condition less likely to occur. It might happen as a side effect of other improvements though. I'd be happy to work on a proper solution, but that would require cooperation from plenty of parties (probably introducing new escape sequences or such), hence it's unlikely to happen. Other than these, I'm not sure how VTE (one particular implementation) could "fix" something that is broken by design, rather by this particular implementation.

**Comment by Tomaszal** [comment]
@egmontkob I understand that a proper solution would be unlikely and it's nice that there are general performance improvements in VTE. However, those improvements aren't really coming across with this bug. Even when I resize a window very slowly and carefully the bug still appears for me. Here's what I mean:

![VTE (Termite)](https://user-images.githubusercontent.com/23457585/42279578-dfb916ea-7fa6-11e8-9497-0c7ec3dc9b3c.gif)

I kind of think it might be more than a race condition, because then it shouldn't really occur in this situation. Yes, it's possible for this bug to occur in URxvt too. However, it takes much more abuse and handles any regular resize scenario just fine.

![URxvt](https://user-images.githubusercontent.com/23457585/42283085-1ae35564-7fb1-11e8-95f1-dcc09abd3d9b.gif)

**Comment by egmontkob** [comment]
urxvt doesn't rewrap its contents until you've reached a screenful of content. (I cannot imagine any sane reason behind this behavior). Until then it's just like xterm, or gnome-terminal with rewrapping disabled.

Can you safely reproduce this difference between gnome-terminal and urxvt after you've produced more than a screenful of content in urxvt?

**Comment by Tomaszal** [comment]
Hmm, yea that's a very odd behavior in urxvt, didn't know that's how it works.

> Can you safely reproduce this difference between gnome-terminal and urxvt after you've produced more than a screenful of content in urxvt?

Yes and no. While the prompt is not at the top of the terminal urxvt resizes almost perfectly, but it shifts the prompt up on occasional resize (probably a race condition too). Once it reaches the top this bug is just as apparent as in VTE terminals.

![urxvt](https://user-images.githubusercontent.com/23457585/42295637-2db018b4-7ff5-11e8-9a91-43c16c03eb7b.gif)

I've actually tried to do the same thing in Termite and it's acting much better when the prompt isn't near the top (very similar to urxvt). Probably a stupid question, but would it maybe be possible to "stick" the prompt to the bottom to aid this?

**Comment by egmontkob** [comment]
> Probably a stupid question, but would it maybe be possible to "stick" the prompt to the bottom to aid this?

You can echo a screenful of newlines at the beginning of your `.zshrc`

**Comment by egmontkob** [comment]
> Probably a stupid question, but would it maybe be possible to "stick" the prompt to the bottom to aid this?

You can echo a screenful of newlines from `.zshrc` at the beginning of your session to move the prompt to the bottom. Not sure though how exactly the prompt being at the bottom makes a difference in any of these emulators.

Figuring out in the terminal emulator what to do exactly for each escape sequence and at a resize event, so that the end result happens to be perfect for zsh's right prompt in particular (and not break any other existing apps), is not a viable approach at all.

**Comment by Tomaszal** [comment]
> You can echo a screenful of newlines from .zshrc at the beginning of your session to move the prompt to the bottom.

That only puts the prompt at the bottom when you open the terminal. It does make a difference somehow, but yea it's not a solution.

![Termite](https://user-images.githubusercontent.com/23457585/42323461-ec45b14e-8068-11e8-8f9f-14ca51e0d2d3.gif)

I guess there's not much VTE can do about it. But could Termite include an option to disable wrapping on resize? I know some other VTE-based terminals let you do that.

**Comment by egmontkob** [comment]
> I guess there's not much VTE can do about it.

Correct. You should raise this issue with zsh developers.

> But could Termite include an option to disable wrapping on resize?

I'm not a Termite developer so I cannot comment on this one.

**Comment by Tomaszal** [comment]
@jelly could Termite include an option to disable wrapping on resize?

**Comment by finex** [comment]
Hi, I've found this bug because I'm experiencing a similar bug (reproducible only using termite, not with other software like konsole). I'm using awesomewm and zsh. When termite window is enlarged the zsh prompt is not locked on the top border but it looks the window is enlarged on top keeping the content locked on bottom. Is related (or maybe the wanted behaviour)?

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
