### ISSUE TITLE
Garbage seen on each startup

### ISSUE THREAD

**Issue by carnager** [thestinger/termite#637]
Every new termite window I open shows garbage on top of the window, which instantly disappears.
Sometimes switch forward and back to other workspaces the garbage re-appears and only disappears until i focus the window or the content changes.

It looks like this:
![img_20181016_165956](https://user-images.githubusercontent.com/3321178/47027636-1097fc00-d168-11e8-9ce8-5b430c7320d6.jpg)

I tried disabling every kind of argb stuff in termite config, but it does not change anything.
I should note that this does not happen with gnome-terminal, which is also vte3 based.

**Comment by apetresc** [comment]
Is this with or without a compositor?

**Comment by foxxx0** [comment]
For me it doesn't change if I use compton or not, it will still show garbled contents before the clean render.

Other system specs (for me):
OS: Arch Linux x64
Kernel: linux-amd-staging-drm-next-git 4.20.782239.99e4bfa530cc (I've been running into some amdgpu problems, but this issue here happens with stable 4.18.x kernels as well)
Xorg: 1.20.1
xf86-video-amdgpu: 18.1.0
Mesa: 18.2.2
i3-wm: 4.14.1

**Comment by goofus** [comment]
I see that too and I also using amdgpu, i3 and arch linux. Does somebody observe this who is not using either i3 or amdgpu?

**Comment by jelly** [comment]
I have an amdgpu with i3 now as well, but I can't reproduce it.

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
