### ISSUE TITLE
clear doesn't prevent scrolling back to output

### ISSUE THREAD

**Issue by ifohancroft** [thestinger/termite#668]
Using Termite version 13, when I execute clear, I can scrollback to the output and I shouldn't be able to.

**Comment by GOKOP** [comment]
But isn't that because of how clear works? It inputs newlines.

**Comment by Narrat** [comment]
Yes, kinda. Although it will use specific ANSI escape sequences if the terminal is ANSI-based.
And even the vte test terminal behaves that way, although the scrollback buffer is reduced. But not completly removed.
AFAIK the only way to make sure, that there is no scrollback buffer, is to use reset instead of clear.

**Comment by egmontkob** [comment]
See https://bugzilla.gnome.org/show_bug.cgi?id=506438#c19. That is, with `clear` from a recent ncurses, this is probably no longer an issue (without requiring the aforementioned change in terminfo).

**Comment by ifohancroft** [comment]
I am closing this as I come to believe we need to have both 'clear' and 'clear scrollback and reset' as sometimes you need one and other times you need the other.
