### ISSUE TITLE
termite as default terminal

### ISSUE THREAD

**Issue by triyan1975** [thestinger/termite#729]
Please. How to set termite as default terminal? I installed termite but default terminal is still xterm. (Arch + i3 + Gnome environment)

**Comment by petrposvic** [comment]
Edit .config/i3/config and change command for $mod+Return:
`
# bindsym $mod+Return exec i3-sensible-terminal
# bindsym $mod+Return exec xterm -bg grey23 -fg silver -fa 'Monospace' -fs 16
bindsym $mod+Return exec termite
`

**Comment by triyan1975** [comment]
It will not help because xdg-open opens vim in xterm

**Comment by ffs97** [comment]
I don't think xdg controls the default terminal [source](https://lists.freedesktop.org/archives/xdg/2015-October/013583.html). Also, in my opinion, this question is not relevant to termite. The reason why xdg is opening vim in xterm might be because you have it set as the default $TERMINAL variable in one of your shell configs (~/.bashrc, ~/.zshrc)

**Comment by AitBits** [comment]
https://specifications.freedesktop.org/mime-apps-spec/latest/

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.
