### ISSUE TITLE
-e should terminate argv parsing and use the remainder of argv as command to run

### ISSUE THREAD

**Issue by r00t-** [thestinger/termite#774]
(instead of taking a regular string argument.)
that's what it does in xterm and many other other terminal emulators.
(gnome-terminal supplies `--` as an alternative.)
this is also necessary to pass "complex" commands, without requiring complex quoting.

consider: ```xterm -e su -c "vi /etc/passwd"```

this is very likely the cause of https://github.com/thestinger/termite/issues/767 (when pacman tries to pass the editor and the file to edit),
and also of https://github.com/raboof/notion/issues/299 .

https://github.com/thestinger/termite/blob/master/termite.cc#L1651

**Comment by zoj613** [comment]
In #767 The `--` wasn't recognised by pcmanfm. After I removed it, the files opened.

**Comment by Apppppppple** [comment]
if termite -e could also return the result of the command ran (assuming --hold was not passed) that would help a lot as well. I'm having to hardcode behavior in some of my scripts when it would make a lot more sense to pipe output from termite.

**Comment by r00t-** [comment]
there's a somewhat similar MR at #717 , but it seems to implement yet another incompatible parsing style

**Comment by PRESFIL** [comment]
IMO, `-e` is most valueable component of `xterm` syntax to be compatible with it. Many programs expect this syntax to be supported, allowing you to change `$0` to any other terminal emulator. But when it comes down to it, `termite` refuses to work. I would like to use termite instead of `xterm`, just by creating a symlink to it.

Sometimes you want to come up with something new, but `xterm` is a defacto standard, which will immediately hit compatibility...

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.

**Comment by zoj613** [comment]
@thestinger thanks for your work on termite. I've thoroughly enjoyed using it. I will follow the recommendations and try out alacritty.
